version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: pull-up-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${SPRING_DATASOURCE_HOST}:3306/pull_up?serverTimezone=UTC&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "13010:13010"
